import type { NetworkLog } from '../types';
import { formatBody } from './parseBody';
import { redact, redactHeaders } from './redact';

export function buildMarkdown(log: NetworkLog): string {
  const statusLabel = log.status === 0 ? 'NETWORK ERROR' : `${log.status}`;
  const lines: string[] = [];

  lines.push(`## ${log.method} \`${log.url}\``);
  lines.push('');
  lines.push(
    '| Field    | Value |',
    '|----------|-------|',
    `| Status   | ${statusLabel} |`,
    `| Duration | ${log.duration}ms |`,
    `| Time     | ${log.timestamp} |`,
  );

  if (log.error) {
    lines.push(`| Error    | \`${log.error}\` |`);
  }

  lines.push('');

  const redactedReqHeaders = redactHeaders(log.reqHeaders);
  if (Object.keys(redactedReqHeaders).length > 0) {
    lines.push('### Request Headers');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(redactedReqHeaders, null, 2));
    lines.push('```');
    lines.push('');
  }

  if (log.reqBody !== null) {
    lines.push('### Request Body');
    lines.push('');
    lines.push('```json');
    lines.push(formatBody(redact(log.reqBody)));
    lines.push('```');
    lines.push('');
  }

  lines.push('### Response Headers');
  lines.push('');
  lines.push('```json');
  lines.push(JSON.stringify(redactHeaders(log.resHeaders), null, 2));
  lines.push('```');
  lines.push('');

  lines.push('### Response Body');
  lines.push('');

  if (log.resBody === null) {
    lines.push('*(empty)*');
  } else {
    lines.push('```json');
    lines.push(formatBody(redact(log.resBody)));
    lines.push('```');
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [HawkLogger](https://github.com/JeelGajera/hawklogger)*');

  return lines.join('\n');
}
