import type { ConsoleLogEntry, NetworkLog } from '../types';
import { formatBody } from './parseBody';
import { redact, redactHeaders, redactStorageSnapshot } from './redact';

export function buildMarkdown(log: NetworkLog): string {
  const statusLabel = log.status === 0 ? 'NETWORK ERROR' : `${log.status}`;
  const lines: string[] = [];

  lines.push(`## ${log.method} \`${log.url}\``);
  lines.push('');
  lines.push(
    '| Field    | Value |',
    '|----------|-------|',
    `| Status   | ${statusLabel} |`,
    `| Duration | ${log.duration}ms |`,
    `| Time     | ${log.timestamp} |`,
  );

  if (log.error) {
    lines.push(`| Error    | \`${log.error}\` |`);
  }

  lines.push('');

  const redactedReqHeaders = redactHeaders(log.reqHeaders);
  if (Object.keys(redactedReqHeaders).length > 0) {
    lines.push('### Request Headers');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(redactedReqHeaders, null, 2));
    lines.push('```');
    lines.push('');
  }

  if (log.reqBody !== null) {
    lines.push('### Request Body');
    lines.push('');
    lines.push('```json');
    lines.push(formatBody(redact(log.reqBody)));
    lines.push('```');
    lines.push('');
  }

  lines.push('### Response Headers');
  lines.push('');
  lines.push('```json');
  lines.push(JSON.stringify(redactHeaders(log.resHeaders), null, 2));
  lines.push('```');
  lines.push('');

  lines.push('### Response Body');
  lines.push('');

  if (log.resBody === null) {
    lines.push('*(empty)*');
  } else {
    lines.push('```json');
    lines.push(formatBody(redact(log.resBody)));
    lines.push('```');
  }

  if (log.consoleLogs != null && log.consoleLogs.length > 0) {
    lines.push('### Console Logs');
    lines.push('');
    lines.push('```text');
    lines.push(formatConsoleLogs(log.consoleLogs));
    lines.push('```');
    lines.push('');
  }

  if (log.storageSnapshot != null) {
    const redactedSnapshot = redactStorageSnapshot(log.storageSnapshot);
    const { cookies, localStorage, sessionStorage, truncated } = redactedSnapshot;

    if (cookies != null && Object.keys(cookies).length > 0) {
      lines.push('### Cookies', '', '```json', JSON.stringify(cookies, null, 2), '```', '');
    }
    if (localStorage != null && Object.keys(localStorage).length > 0) {
      lines.push('### Local Storage', '', '```json', JSON.stringify(localStorage, null, 2), '```', '');
    }
    if (sessionStorage != null && Object.keys(sessionStorage).length > 0) {
      lines.push('### Session Storage', '', '```json', JSON.stringify(sessionStorage, null, 2), '```', '');
    }
    if (truncated) {
      lines.push('*(snapshot truncated - some entries were omitted)*', '');
    }
  }

  lines.push('---');
  lines.push('*Generated by [HawkLogger](https://github.com/JeelGajera/hawklogger)*');

  return lines.join('\n');
}

function formatConsoleLogs(entries: ConsoleLogEntry[]): string {
  return entries
    .map((entry) => `[${formatTime(entry.timestamp)}] ${entry.level.toUpperCase()}: ${entry.message}`)
    .join('\n');
}

function formatTime(isoTimestamp: string): string {
  const date = new Date(isoTimestamp);
  return Number.isNaN(date.getTime()) ? isoTimestamp : date.toISOString().slice(11, 23);
}
